// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btfbaepwquwrhlpqdwtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZmJhZXB3cXV3cmhscHFkd3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDYzNDYsImV4cCI6MjA2NTU4MjM0Nn0.pQ9gB3QMqbqjJGejtFL7A_kFChgAOafZx3ockEnMNLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);